In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset=dataset.drop("User ID",axis=1)

In [5]:
dataset.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [7]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [10]:
dataset=dataset.astype(int)

In [11]:
dataset.head()

   Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0            1
1   35            20000          0            1
2   26            43000          0            0
3   27            57000          0            0
4   19            76000          0            1

In [13]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset[["Purchased"]]

In [14]:
indep.head()

   Age  EstimatedSalary  Gender_Male
0   19            19000            1
1   35            20000            1
2   26            43000            0
3   27            57000            0
4   19            76000            1

In [15]:
dep.head()

   Purchased
0          0
1          0
2          0
3          0
4          0

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(indep,dep,test_size=0.3,random_state=0)

In [19]:
x_train,x_test,y_train,y_test

(     Age  EstimatedSalary  Gender_Male
 92    26            15000            1
 223   60           102000            1
 234   38           112000            0
 232   40           107000            1
 377   42            53000            0
 ..   ...              ...          ...
 323   48            30000            0
 192   29            43000            1
 117   36            52000            1
 47    27            54000            0
 172   26           118000            0

 [280 rows x 3 columns],
      Age  EstimatedSalary  Gender_Male
 132   30            87000            1
 309   38            50000            0
 341   35            75000            1
 196   30            79000            0
 246   35            50000            0
 ..   ...              ...          ...
 216   49            65000            1
 259   45           131000            0
 49    31            89000            0
 238   46            82000            0
 343   47            51000            0

 [120 rows x 3 columns],
      Purchased
 92           0
 223          1
 234          0
 232          1
 377          0
 ..         ...
 323          1
 192          0
 117          0
 47           0
 172          0

 [280 rows x 1 columns],
      Purchased
 132          0
 309          0
 341          0
 196          0
 246          0
 ..         ...
 216          0
 259          1
 49           0
 238          0
 343          1

 [120 rows x 1 columns])

In [20]:
#Model creation

In [22]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=7)

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
y_pred=classifier.predict(x_test)

In [25]:
cm=confusion_matrix(y_test,y_pred)

In [26]:
from sklearn.metrics import classification_report

In [27]:
clf_report=classification_report(y_test,y_pred)

In [28]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.85      0.91      0.88        79
           1       0.80      0.68      0.74        41

    accuracy                           0.83       120
   macro avg       0.82      0.80      0.81       120
weighted avg       0.83      0.83      0.83       120

In [29]:
print(cm)

[[72  7]
 [13 28]]

In [30]:
classifier.predict([[40,60000,1]])

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])