In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import numpy as np

In [5]:
data= pd.read_csv("CKD.csv")

In [6]:
data

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [7]:
data['classification'].value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [8]:
data=pd.get_dummies(data,drop_first=True)
data=data.astype(int)
data

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [9]:
indep=data.iloc[:,0:27].values
dep=data['classification_yes']

In [10]:
indep

array([[ 2, 76,  3, ...,  1,  1,  0],
       [ 3, 76,  2, ...,  1,  0,  0],
       [ 4, 76,  1, ...,  1,  0,  0],
       ...,
       [51, 70,  3, ...,  0,  0,  0],
       [51, 90,  0, ...,  1,  0,  1],
       [51, 80,  0, ...,  1,  0,  0]])

In [11]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(indep,dep,test_size=0.3,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [14]:
#Gaussian Naive bayes - got error ( ValueError: Negative values in data passed to MultinomialNB (input X))

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB

# Create an untuned KNN model
clf = GaussianNB()

# Define the parameter grid
param_grid = {
    'var_smoothing': np.logspace(0, -9, num=100)
}

# Create a GridSearchCV object
grid = GridSearchCV(clf, param_grid, cv=5)

# Fit the grid search object to the data
grid.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.31...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])})

In [16]:
best_params = grid.best_params_

In [17]:
print(best_params)

{'var_smoothing': 0.006579332246575682}

In [18]:
re=grid.cv_results_

In [19]:
grid_predictions=grid.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,grid_predictions)

In [21]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [22]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

In [23]:
print(cm)

[[45  0]
 [ 1 74]]

In [24]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'var_smoothing': 0.006579332246575682}: 0.9916844900066377

In [25]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [26]:
table=pd.DataFrame.from_dict(re)

In [27]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_var_smoothing,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002498,0.001928,0.000788,0.000744,1.0,{'var_smoothing': 1.0},0.750000,0.803571,0.732143,0.839286,0.909091,0.806818,0.063764,100
1,0.002015,0.002543,0.004718,0.003771,0.811131,{'var_smoothing': 0.8111308307896871},0.750000,0.803571,0.750000,0.857143,0.909091,0.813961,0.061975,99
2,0.002211,0.001528,0.003864,0.003240,0.657933,{'var_smoothing': 0.657933224657568},0.767857,0.857143,0.767857,0.875000,0.927273,0.839026,0.062514,98
3,0.003446,0.006892,0.000000,0.000000,0.53367,{'var_smoothing': 0.533669923120631},0.803571,0.875000,0.821429,0.892857,0.945455,0.867662,0.050962,97
4,0.000393,0.000785,0.006264,0.007672,0.432876,{'var_smoothing': 0.43287612810830584},0.839286,0.892857,0.875000,0.928571,0.963636,0.899870,0.042961,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.000000,0.000000,0.003124,0.006248,0.0,{'var_smoothing': 2.310129700083158e-09},0.982143,1.000000,0.946429,1.000000,0.981818,0.982078,0.019562,29
96,0.003124,0.006249,0.000000,0.000000,0.0,{'var_smoothing': 1.873817422860387e-09},0.982143,1.000000,0.946429,1.000000,0.981818,0.982078,0.019562,29
97,0.003124,0.006248,0.000000,0.000000,0.0,{'var_smoothing': 1.519911082952933e-09},0.982143,1.000000,0.946429,1.000000,0.981818,0.982078,0.019562,29
98,0.003125,0.006249,0.000000,0.000000,0.0,{'var_smoothing': 1.2328467394420635e-09},0.982143,1.000000,0.946429,1.000000,0.981818,0.982078,0.019562,29
99,0.000000,0.000000,0.003124,0.006249,0.0,{'var_smoothing': 1e-09},0.982143,1.000000,0.946429,1.000000,0.981818,0.982078,0.019562,29

In [28]:
import pickle

In [29]:
filename="finalized_model_Gaussian Naive Bayes_GridClassification.sav"

In [30]:
pickle.dump(grid ,open(filename,'wb'))

In [31]:
preinput=sc.transform([[6,82,1,95,17,0,137,3,12,38,7500,5.4,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1]])

In [32]:
loaded_model=pickle.load(open("finalized_model_Gaussian Naive Bayes_GridClassification.sav",'rb'))

In [33]:
result=loaded_model.predict(preinput)

In [34]:
result

array([1])