In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data= pd.read_csv("CKD.csv")

In [3]:
data

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
data.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hrmo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [5]:
data.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [6]:
data=pd.get_dummies(data,drop_first=True)

In [7]:
data=data.astype(int)

In [8]:
data.head()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1

In [10]:
data["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [11]:
indep= data.iloc[:,0:27].values

In [12]:
indep

array([[ 2, 76,  3, ...,  1,  1,  0],
       [ 3, 76,  2, ...,  1,  0,  0],
       [ 4, 76,  1, ...,  1,  0,  0],
       ...,
       [51, 70,  3, ...,  0,  0,  0],
       [51, 90,  0, ...,  1,  0,  1],
       [51, 80,  0, ...,  1,  0,  0]])

In [13]:
dep=data['classification_yes']

In [14]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test= train_test_split(indep,dep,test_size=0.3,random_state=0)

In [17]:
x_train,x_test,y_train,y_test

(array([[ 41,  80,   1, ...,   1,   0,   0],
        [ 57,  80,   0, ...,   1,   0,   0],
        [ 59, 100,   4, ...,   1,   0,   1],
        ...,
        [ 45,  80,   0, ...,   1,   0,   0],
        [ 30,  80,   0, ...,   1,   0,   0],
        [ 51,  60,   0, ...,   1,   0,   0]]),
 array([[46, 70,  0, ...,  1,  0,  0],
        [66, 90,  2, ...,  0,  0,  0],
        [69, 70,  0, ...,  1,  0,  0],
        ...,
        [30, 60,  0, ...,  1,  0,  0],
        [59, 60,  0, ...,  1,  0,  0],
        [70, 60,  0, ...,  1,  0,  0]]),
 92     1
 223    0
 234    1
 232    1
 336    1
       ..
 323    1
 192    1
 117    1
 47     0
 172    0
 Name: classification_yes, Length: 279, dtype: int32,
 132    0
 309    1
 334    0
 196    1
 246    1
       ..
 216    1
 259    1
 49     0
 238    0
 342    0
 Name: classification_yes, Length: 120, dtype: int32)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 



grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(x_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\USER\anaconda3\envs\AI_Project\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.96792562 0.97142573 0.95362667 0.96790409
        nan        nan 0.94672045 0.96405452 0.93937321 0.96437516]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [22]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(x_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [23]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'random'}: 0.9584224500331883

In [24]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[43  2]
 [ 3 72]]

In [25]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.93      0.96      0.95        45
           1       0.97      0.96      0.97        75

    accuracy                           0.96       120
   macro avg       0.95      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120

In [26]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9577777777777778

In [27]:
table=pd.DataFrame.from_dict(re)

In [28]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001397,0.000490,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000913,0.000169,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.003834,0.002130,0.005445,0.000954,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982051,0.982051,0.929513,0.964286,0.981728,0.967926,0.020388,2
3,0.003152,0.001401,0.007422,0.004389,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.964286,0.946663,0.964286,0.981894,0.971426,0.018117,1
4,0.002964,0.001039,0.007416,0.002430,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.928571,0.912029,0.964286,0.963247,0.953627,0.030707,6
5,0.002029,0.000067,0.004240,0.000395,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.946663,0.964286,0.964286,0.964286,1.000000,0.967904,0.017439,3
6,0.000999,0.000003,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.001320,0.000268,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.002197,0.000404,0.005079,0.000876,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.982221,0.910254,0.876841,0.964286,1.000000,0.946720,0.046088,7
9,0.002605,0.000364,0.004488,0.000622,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.964286,0.982051,1.000000,0.946663,0.927273,0.964055,0.025579,5
10,0.002415,0.000596,0.004568,0.001096,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.911105,0.911692,0.946663,0.945185,0.939373,0.026413,8
11,0.002395,0.000491,0.004960,0.001284,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.947015,0.946663,0.964286,0.963912,0.964375,0.019414,4

In [29]:
import pickle

In [30]:
filename="finalized_model_DT_GridClassification.sav"

In [31]:
pickle.dump(grid ,open(filename,'wb'))

In [32]:
#Standardscaler

In [33]:
data.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [34]:
data.head()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1

In [36]:
preinput=sc.transform([[6,82,1,95,17,0,137,3,12,38,7500,5.4,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1]])

In [37]:
loaded_model=pickle.load(open("finalized_model_DT_GridClassification.sav",'rb'))

In [38]:
result=loaded_model.predict(preinput)

In [39]:
result

array([1])