In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('insurance_pre.csv')

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)

In [6]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [7]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [10]:
from sklearn.ensemble import RandomForestRegressor

In [11]:
from sklearn.model_selection import GridSearchCV

In [12]:
param_grid = {'criterion':['friedman_mse','squared_error','absolute_error','poisson'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(),param_grid, refit = True, verbose= 3,n_jobs=-1)

In [13]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.78327901 0.79875775 0.77541912 0.79654043
        nan        nan 0.78178381 0.79642212 0.76529933 0.7959261
        nan        nan 0.78120745 0.79812033 0.78268206 0.80177821
        nan        nan 0.77832125 0.79739203 0.78587311 0.79541302]
  warnings.warn(

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [14]:
re=grid.cv_results_
grid_predictions = grid.predict(x_test)

from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}: 0.8707904815345425

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003326,0.006165,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.000691,0.000530,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.055869,0.003734,0.007803,0.008743,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.775810,0.765220,0.810058,0.807159,0.758150,0.783279,0.021451,10
3,0.600916,0.044331,0.019290,0.006530,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.802239,0.772283,0.832883,0.829105,0.757279,0.798758,0.030063,2
4,0.051598,0.007437,0.003152,0.006305,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.782226,0.755811,0.804622,0.803054,0.731383,0.775419,0.028236,15
5,0.597408,0.059241,0.025403,0.007993,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.805173,0.769218,0.827918,0.826234,0.754160,0.796540,0.029945,5
6,0.000576,0.000758,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.000200,0.000399,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.050018,0.009575,0.003691,0.007382,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.791062,0.744789,0.825757,0.827873,0.719438,0.781784,0.043358,12
9,0.691330,0.197404,0.025766,0.012657,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.810238,0.765624,0.830876,0.821786,0.753587,0.796422,0.030999,6
10,0.046966,0.002525,0.000000,0.000000,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.777489,0.726091,0.807641,0.795780,0.719495,0.765299,0.036072,16
11,1.018748,0.119466,0.045320,0.014442,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.806750,0.756569,0.836641,0.825969,0.753702,0.795926,0.034668,7
12,0.001647,0.003294,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.000000,0.000000,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.278781,0.016994,0.015621,0.017112,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.778489,0.735428,0.834749,0.811436,0.745935,0.781207,0.037757,13
15,2.665035,0.101189,0.041652,0.013507,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.805261,0.771312,0.835312,0.824406,0.754311,0.798120,0.030864,3
16,0.264026,0.025623,0.009823,0.008061,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.798844,0.750394,0.825324,0.808848,0.730001,0.782682,0.036282,11
17,2.734637,0.032848,0.031515,0.000544,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.806513,0.773191,0.843023,0.829668,0.756496,0.801778,0.032769,1
18,0.003137,0.006273,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.000000,0.000000,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.137443,0.023094,0.003124,0.006249,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.774807,0.748525,0.817434,0.814249,0.736591,0.778321,0.033052,14
21,1.303839,0.039183,0.040979,0.013135,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.810757,0.762425,0.830019,0.829309,0.754450,0.797392,0.032645,4
22,0.131174,0.015054,0.003125,0.006249,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.792982,0.760311,0.800839,0.814375,0.760859,0.785873,0.021753,9
23,1.181412,0.106089,0.037491,0.012497,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.803863,0.766476,0.828634,0.827027,0.751065,0.795413,0.031555,8

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:40
BMI:51
Children:3
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[16544.785]