In [3]:
import pickle

In [5]:
import pandas as pd

In [6]:
data= pd.read_csv("50_Startups.csv")

In [7]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [8]:
data= pd.get_dummies(data,drop_first=True)

In [9]:
data=data.astype(int)

In [10]:
data.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0

In [11]:
independent=data[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]

In [12]:
independent.head()

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0     165349          136897           471784              0               1
1     162597          151377           443898              0               0
2     153441          101145           407934              1               0
3     144372          118671           383199              0               1
4     142107           91391           366168              1               0

In [13]:
dependent=data[['Profit']]

In [14]:
dependent.head()

   Profit
0  192261
1  191792
2  191050
3  182901
4  166187

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [16]:
x_train,x_test,y_train,y_test

(    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
 7      130298          145530           323876              1               0
 14     119943          156547           256512              1               0
 45       1000          124153             1903              0               1
 48        542           51743                0              0               1
 29      65605          153032           107138              0               1
 15     114523          122616           261776              0               1
 30      61994          115641            91131              1               0
 32      63408          129219            46085              0               0
 16      78013          121597           264346              0               0
 42      23640           96189           148001              0               0
 20      76253          113867           298664              0               0
 43      15505          127382            35534              0               1
 8      120542          148718           311613              0               1
 13      91992          135495           252664              0               0
 25      64664          139553           137962              0               0
 5      131876           99814           362861              0               1
 17      94657          145077           282574              0               1
 40      28754          118546           172795              0               0
 49          0          116983            45173              0               0
 1      162597          151377           443898              0               0
 12      93863          127320           249839              1               0
 37      44069           51283           197029              0               0
 24      77044           99281           140574              0               1
 6      134615          147198           127716              0               0
 23      67532          105751           304768              1               0
 36      28663          127056           201126              1               0
 21      78389          153773           299737              0               1
 19      86419          153514                0              0               1
 9      123334          108679           304981              0               0
 39      38558           82982           174999              0               0
 46       1315          115816           297114              1               0
 3      144372          118671           383199              0               1
 0      165349          136897           471784              0               1
 47          0          135426                0              0               0
 44      22177          154806            28334              0               0,
     R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
 28      66051          182645           118148              1               0
 11     100671           91790           249744              0               0
 10     101913          110594           229160              1               0
 41      27892           84710           164470              1               0
 2      153441          101145           407934              1               0
 27      72107          127864           353183              0               1
 38      20229           65947           185265              0               1
 31      61136          152701            88218              0               1
 22      73994          122782           303319              1               0
 4      142107           91391           366168              1               0
 33      55493          103057           214634              1               0
 35      46014           85047           205517              0               1
 26      75328          144135           134050              1               0
 34      46426          157693           210797              0               0
 18      91749          114175           294919              1               0,
     Profit
 7   155752
 14  132602
 45   64926
 48   35673
 29  101004
 15  129917
 30   99937
 32   97427
 16  126992
 42   71498
 20  118474
 43   69758
 8   152211
 13  134307
 25  107404
 5   156991
 17  125370
 40   78239
 49   14681
 1   191792
 12  141585
 37   89949
 24  108552
 6   156122
 23  108733
 36   90708
 21  111313
 19  122776
 9   149759
 39   81005
 46   49490
 3   182901
 0   192261
 47   42559
 44   65200,
     Profit
 28  103282
 11  144259
 10  146121
 41   77798
 2   191050
 27  105008
 38   81229
 31   97483
 22  110352
 4   166187
 33   96778
 35   96479
 26  105733
 34   96712
 18  124266)

In [17]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test =sc.transform(x_test)

In [18]:
preinput=sc.transform([[1300,1200,4000,0,1]])

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [19]:
loaded_model=pickle.load(open("finalized_model_SVR.sav",'rb'))

In [20]:
result=loaded_model.predict(preinput)

In [21]:
result

array([108597.61910246])