In [1]:
import pandas as pd

In [2]:
data= pd.read_csv("50_Startups.csv")

In [3]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data= pd.get_dummies(data,drop_first=True)

In [5]:
data=data.astype(int)

In [6]:
data.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0

In [7]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [8]:
independent=data[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]

In [9]:
independent.head()

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0     165349          136897           471784              0               1
1     162597          151377           443898              0               0
2     153441          101145           407934              1               0
3     144372          118671           383199              0               1
4     142107           91391           366168              1               0

In [10]:
dependent=data[['Profit']]

In [11]:
dependent.head()

   Profit
0  192261
1  191792
2  191050
3  182901
4  166187

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [17]:
x_train,x_test,y_train,y_test

(array([[ 1.17644918,  0.84516741,  0.94354831,  2.        , -0.76870611],
        [ 0.964209  ,  1.27283753,  0.42738466,  2.        , -0.76870611],
        [-1.47369376,  0.01533133, -1.52350767, -0.5       ,  1.30088727],
        [-1.48308111, -2.79556033, -1.53808904, -0.5       ,  1.30088727],
        [-0.14952413,  1.13638837, -0.71716479, -0.5       ,  1.30088727],
        [ 0.85311854, -0.04433364,  0.46771904, -0.5       ,  1.30088727],
        [-0.22353662, -0.31509692, -0.83981534,  2.        , -0.76870611],
        [-0.19455471,  0.21198893, -1.18497162, -0.5       , -0.76870611],
        [ 0.10479514, -0.08389031,  0.48741117, -0.5       , -0.76870611],
        [-1.00965537, -1.07020622, -0.40405994, -0.5       , -0.76870611],
        [ 0.06872149, -0.38396202,  0.75036622, -0.5       , -0.76870611],
        [-1.17639355,  0.14067823, -1.26581662, -0.5       ,  1.30088727],
        [ 0.97648634,  0.96892273,  0.84958544, -0.5       ,  1.30088727],
        [ 0.39131425,  0.45561766,  0.3979001 , -0.5       , -0.76870611],
        [-0.16881124,  0.6131456 , -0.48098184, -0.5       , -0.76870611],
        [ 1.20879249, -0.92948696,  1.24226335, -0.5       ,  1.30088727],
        [ 0.44593715,  0.82758236,  0.6270797 , -0.5       ,  1.30088727],
        [-0.9048368 , -0.20232741, -0.2140807 , -0.5       , -0.76870611],
        [-1.49419016, -0.26300168, -1.19195964, -0.5       , -0.76870611],
        [ 1.83846226,  1.07214274,  1.86319372, -0.5       , -0.76870611],
        [ 0.42966301,  0.13827145,  0.37625408,  2.        , -0.76870611],
        [-0.59093451, -2.81341712, -0.02839235, -0.5       , -0.76870611],
        [ 0.08493413, -0.95017754, -0.46096789, -0.5       ,  1.30088727],
        [ 1.26493212,  0.90991769, -0.55948984, -0.5       , -0.76870611],
        [-0.11002758, -0.69901791,  0.79713695,  2.        , -0.76870611],
        [-0.90670197,  0.1280232 ,  0.00300012,  2.        , -0.76870611],
        [ 0.11250179,  1.16515333,  0.75858788, -0.5       ,  1.30088727],
        [ 0.27708784,  1.15509918, -1.53808904, -0.5       ,  1.30088727],
        [ 1.03371228, -0.58535556,  0.79876902, -0.5       , -0.76870611],
        [-0.70389014, -1.58289019, -0.19719297, -0.5       , -0.76870611],
        [-1.4672374 , -0.30830358,  0.73848965,  2.        , -0.76870611],
        [ 1.46491545, -0.19747502,  1.39809935, -0.5       ,  1.30088727],
        [ 1.89486834,  0.51004205,  2.07686481, -0.5       ,  1.30088727],
        [-1.49419016,  0.45293914, -1.53808904, -0.5       , -0.76870611],
        [-1.03964159,  1.20525347, -1.32098523, -0.5       , -0.76870611]]),
 array([[-0.14038274,  2.28593863, -0.63280279,  2.        , -0.76870611],
        [ 0.56920247, -1.24097148,  0.37552616, -0.5       , -0.76870611],
        [ 0.59465899, -0.51101696,  0.21780524,  2.        , -0.76870611],
        [-0.92250469, -1.51581077, -0.2778694 ,  2.        , -0.76870611],
        [ 1.65079726, -0.87781872,  1.58762651,  2.        , -0.76870611],
        [-0.01625657,  0.15938904,  1.16810754, -0.5       ,  1.30088727],
        [-1.07956857, -2.24417371, -0.11853173, -0.5       ,  1.30088727],
        [-0.24112252,  1.12353924, -0.86213564, -0.5       ,  1.30088727],
        [ 0.02242013, -0.03788967,  0.78603426,  2.        , -0.76870611],
        [ 1.41849111, -1.25646031,  1.2676026 ,  2.        , -0.76870611],
        [-0.35678368, -0.80359659,  0.10650256,  2.        , -0.76870611],
        [-0.55106902, -1.50272873,  0.03664531, -0.5       ,  1.30088727],
        [ 0.04976232,  0.79101476, -0.51095678,  2.        , -0.76870611],
        [-0.5426245 ,  1.31732423,  0.07710229, -0.5       , -0.76870611],
        [ 0.38633363, -0.37200574,  0.72167088,  2.        , -0.76870611]]),
     Profit
 7   155752
 14  132602
 45   64926
 48   35673
 29  101004
 15  129917
 30   99937
 32   97427
 16  126992
 42   71498
 20  118474
 43   69758
 8   152211
 13  134307
 25  107404
 5   156991
 17  125370
 40   78239
 49   14681
 1   191792
 12  141585
 37   89949
 24  108552
 6   156122
 23  108733
 36   90708
 21  111313
 19  122776
 9   149759
 39   81005
 46   49490
 3   182901
 0   192261
 47   42559
 44   65200,
     Profit
 28  103282
 11  144259
 10  146121
 41   77798
 2   191050
 27  105008
 38   81229
 31   97483
 22  110352
 4   166187
 33   96778
 35   96479
 26  105733
 34   96712
 18  124266)

In [14]:
# Using Advanced preprocessing Technique input X and output Y

In [15]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test =sc.transform(x_test)

In [18]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [30]:
from sklearn.svm import SVR

In [31]:
regressor = SVR(kernel="linear")

In [32]:
regressor.fit(x_train,y_train)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='linear')

In [33]:
SVR()

SVR()

In [34]:
regressor.intercept_

array([0.00712276])

In [35]:
regressor.n_support_

array([19])

In [36]:
regressor.support_

array([ 0,  1,  2,  3,  5,  8, 11, 13, 16, 18, 20, 21, 23, 25, 26, 27, 30,
       31, 33])

In [37]:
y_pred = regressor.predict(x_test)

In [38]:
from sklearn.metrics import r2_score
r_score= r2_score(y_test,y_pred)

In [39]:
r_score

0.9376726018989979

In [40]:
import pickle

In [41]:
filename="finalized_model_SVR.sav"

In [42]:
pickle.dump(regressor,open(filename,'wb'))

In [43]:
preinput=sc.transform([[1300,1200,4000,0,1]])

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [47]:
preoutput=scy.inverse_transform([result])
preoutput

array([[45911.88231251]])

In [48]:
loaded_model=pickle.load(open("finalized_model_SVR.sav",'rb'))

In [49]:
result=loaded_model.predict(preinput)

In [50]:
result

array([-1.49520595])